services:
  postgres-employee:
    container_name: lf8Starter_postgres
    image: postgres:16.4
    environment:
      POSTGRES_DB: lf8Starter
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - lf8Starter_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    container_name: lf8Starter_keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-employee
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: secret
      KC_DB_URL_DATABASE: lf8Starter
      KC_DB_SCHEMA: public
    command: start-dev --import-realm
    depends_on:
      - postgres-employee
    volumes:
      - ./docker/keycloak/realm.json:/opt/keycloak/data/import/realm.json
      - lf8Starter_keycloak_data:/opt/keycloak/data
    ports:
      - "8180:8080"

volumes:
  lf8Starter_postgres_data:
  lf8Starter_keycloak_data:
