volumes:
  lf8Starter_postgres_data:
    driver: local

services:
  keycloak:
    container_name: lf8Starter_keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    volumes:
      - ./docker/keycloak/realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - "8080:8080"
  postgres-employee:
    container_name: lf8Starter_postgres
    image: postgres:16.4
    volumes:
      - lf8Starter_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lf8Starter
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"